[package]
name = "wasm-protobuf-gen-build"
version = "0.0.1"
authors = ["David Ross <daboross@daboross.net>"]

[dependencies]
syn = { version = "0.11", features = ["full"] }
quote = "0.3"
failure = "0.1.0"
failure_derive = "0.1.0"
arrayvec = "0.4"
