[package]
name = "wasm-protobuf-gen-impl"
version = "0.0.1"
authors = ["David Ross <daboross@daboross.net>"]

[dependencies]
proc-macro-hack = "0.4"
syn = { version = "0.11", features = ["full"] }
quote = "0.3"

[lib]
proc-macro = true
